version: "3.8"
services:
  server:
    build:
      context: ./server
    volumes:
      - ./server:/app # Mount the local server directory into the container
    ports:
      - "8080:8080" # Map port 8080 for the server
    networks:
      - app-network

  client:
    build:
      context: ./client
    volumes:
      - ./client:/app # Mount the local client directory into the container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
