version: "3.8"
services:
  client:
    container_name: client
    build:
      context: ./client
    working_dir: /app/client
    volumes:
      - ./shared:/app/shared
    networks:
      - app-network
    depends_on:
      - router
    stdin_open: true
    tty: true

  router:
    container_name: router
    build:
      context: ./router
    working_dir: /app/router
    volumes:
      - ./shared:/app/shared
    networks:
      - app-network
    depends_on:
      - server1
      - server2
      - server3
    ports:
      - "5432:5432"
    command: ["./router"]

  server1:
    container_name: server1
    build:
      context: ./server
    working_dir: /app/server
    volumes:
      - ./shared:/app/shared
    networks:
      - app-network
    command: ["./server"]

  server2:
    container_name: server2
    build:
      context: ./server
    working_dir: /app/server
    volumes:
      - ./shared:/app/shared
    networks:
      - app-network
    command: ["./server"]

  server3:
    container_name: server3
    build:
      context: ./server
    working_dir: /app/server
    volumes:
      - ./shared:/app/shared
    networks:
      - app-network
    command: ["./server"]

networks:
  app-network:
    driver: bridge
