version: "3.8"
services:
  server:
    build:
      context: ./server
    ports:
      - "5432:5432" # Map port 5432 for the server
    networks:
      - app-network

  client:
    build:
      context: ./client
    networks:
      - app-network
    depends_on:
      - server # Ensure the server starts before the client
    command: ["./client", "server"] # Run the client with "server" as the hostname

networks:
  app-network:
    driver: bridge
