FROM gcc:latest

# Set the working directory
WORKDIR /shared/server/

# Copy the source code into the container
COPY server.c /shared/server/

# Compile the source code into an executable
# RUN make

# Expose the server port
EXPOSE 5432

# Set the default command to run the server
# CMD ["./server"]
